import { EffectId } from "./effects";
import {
  CardKind,
  District,
  EffectType,
  ExecutiveSide,
  MonumentId,
  PartyId,
  PolicyId,
  PolicySide,
  Symbol,
  TriggerWhen,
  type ExecutiveCard,
  type MonumentCard,
  type PartyCard,
  type PolicyCard,
} from "./schema";

export const PARTIES: PartyCard[] = [
  {
    id: PartyId.Trinity,
    kind: CardKind.Party,
    name: "Trinity Party",
    order: 1,
    symbol: Symbol.Crown,
    startingCards: [
      { name: "Architecture Inc.", district: District.Shavvinne },
      { name: "Divine Inquisitors", district: District.Shavvinne },
      { name: "Roman Church", district: District.Shavvinne },
      { name: "Fundamentalists", district: District.Smarbbit },
    ],
    guaranteedMonumentId: MonumentId.RomanBasilica,
    art: "/cards/parties/party-1.png",
  },
  {
    id: PartyId.Conservative,
    kind: CardKind.Party,
    name: "Conservative Party",
    order: 2,
    symbol: Symbol.Crown,
    startingCards: [
      { name: "Capitol Inc.", district: District.Smarbbit },
      { name: "Project Habitat", district: District.Smarbbit },
      { name: "Conservatives", district: District.Smarbbit },
      { name: "Estate Moguls", district: District.Horsard },
    ],
    guaranteedMonumentId: MonumentId.SmartDoctrine,
    art: "/cards/parties/party-2.png",
  },
  {
    id: PartyId.Progressive,
    kind: CardKind.Party,
    name: "Progressive Party",
    order: 3,
    symbol: Symbol.Atom,
    startingCards: [
      { name: "District Governor", district: District.Dragonara },
      { name: "Urban Aristocrats", district: District.Dragonara },
      { name: "Grand Justices", district: District.Dragonara },
      { name: "Royal Academy", district: District.Shavvinne },
    ],
    guaranteedMonumentId: MonumentId.IntelNetwork,
    art: "/cards/parties/party-3.png",
  },
  {
    id: PartyId.Innovative,
    kind: CardKind.Party,
    name: "Innovative Party",
    order: 4,
    symbol: Symbol.Atom,
    startingCards: [
      { name: "Financial Bankers", district: District.Horsard },
      { name: "Foreign Inc.", district: District.Horsard },
      { name: "Professors", district: District.Dragonara },
      { name: "Regulators", district: District.Horsard },
    ],
    guaranteedMonumentId: MonumentId.SpaceAgency,
    art: "/cards/parties/party-4.png",
  },
  {
    id: PartyId.Liberal,
    kind: CardKind.Party,
    name: "Liberal Party",
    order: 5,
    symbol: Symbol.Chart,
    startingCards: [
      { name: "Rebel Inc.", district: District.Shavvinne },
      { name: "Film Industry", district: District.Horsard },
      { name: "Liberalists", district: District.Smarbbit },
      { name: "Influencers", district: District.Horsard },
    ],
    guaranteedMonumentId: MonumentId.PlanetNext,
    art: "/cards/parties/party-5.png",
  },
  {
    id: PartyId.Global,
    kind: CardKind.Party,
    name: "Global Party",
    order: 6,
    symbol: Symbol.Scales,
    startingCards: [
      { name: "People's Press", district: District.Smarbbit },
      { name: "Export Giants", district: District.Horsard },
      { name: "Robot Factories", district: District.Dragonara },
      { name: "Export Bureau", district: District.Dragonara },
    ],
    guaranteedMonumentId: MonumentId.DragonGate,
    art: "/cards/parties/party-6.png",
  },
  {
    id: PartyId.Socialist,
    kind: CardKind.Party,
    name: "Socialist Party",
    order: 7,
    symbol: Symbol.Scales,
    startingCards: [
      { name: "State Enterprise", district: District.Dragonara },
      { name: "Communists", district: District.Smarbbit },
      { name: "Socialists", district: District.Smarbbit },
      { name: "Local Politicians", district: District.Shavvinne },
    ],
    guaranteedMonumentId: MonumentId.ModelSociety,
    art: "/cards/parties/party-7.png",
  },
  {
    id: PartyId.Republican,
    kind: CardKind.Party,
    name: "Republican Party",
    order: 8,
    symbol: Symbol.Chart,
    startingCards: [
      { name: "Century Club", district: District.Horsard },
      { name: "Civic Council", district: District.Dragonara },
      { name: "Emirates", district: District.Shavvinne },
      { name: "Monarch Family", district: District.Shavvinne },
    ],
    guaranteedMonumentId: MonumentId.CivilService,
    art: "/cards/parties/party-8.png",
  },
];

export const MONUMENTS: MonumentCard[] = [
  {
    id: MonumentId.IntelNetwork,
    kind: CardKind.Monument,
    name: "Intel Network",
    district: District.Dragonara,
    symbols: [Symbol.Atom],
    text: "As a free action, you may inspect the top 5 cards of the draw deck, then move one to top of the deck.",
    effects: [
      {
        type: EffectType.FreeAction,
        id: EffectId.InspectTopFiveMoveOneToTop,
      },
    ],
    art: "/cards/monuments/intel-network.png",
  },
  {
    id: MonumentId.DragonGate,
    kind: CardKind.Monument,
    name: "Dragon Gate",
    district: District.Dragonara,
    symbols: [Symbol.Scales],
    text: "You now have +2 hand limit. Draw a card at the end of income step if you have exactly 4 cards.",
    effects: [
      { type: EffectType.Static, id: EffectId.PlusTwoHandLimitDrawAtFour },
    ],
    art: "/cards/monuments/dragon-gate.png",
  },
  {
    id: MonumentId.PlanetNext,
    kind: CardKind.Monument,
    name: "Planet Next",
    district: District.Horsard,
    symbols: [Symbol.Chart],
    text: "Before election results, you may discard cards that each gives matching district +2 influence.",
    effects: [
      {
        type: EffectType.Triggered,
        id: EffectId.PlanetNextElectionDiscard,
        when: TriggerWhen.BeforeElectionTally,
      },
    ],
    art: "/cards/monuments/planet-next.png",
  },
  {
    id: MonumentId.SpaceAgency,
    kind: CardKind.Monument,
    name: "Space Agency",
    district: District.Horsard,
    symbols: [Symbol.Atom],
    text: "You may discard cards to other support piles as long as you only discard up to 1 in each of those.",
    effects: [
      { type: EffectType.Static, id: EffectId.SpaceAgencyRerouteDiscards },
    ],
    art: "/cards/monuments/space-agency.png",
  },
  {
    id: MonumentId.RomanBasilica,
    kind: CardKind.Monument,
    name: "Roman Basilica",
    district: District.Shavvinne,
    symbols: [Symbol.Crown],
    text: "You always win Civil Victory at the end of final election regardless of election wins.",
    effects: [{ type: EffectType.Static, id: EffectId.AlwaysWinCivil }],
    art: "/cards/monuments/roman-basilica.png",
  },
  {
    id: MonumentId.CivilService,
    kind: CardKind.Monument,
    name: "Civil Service",
    district: District.Shavvinne,
    symbols: [Symbol.Chart],
    text: "Opponent cannot win a district where they don't have more civil cards.",
    effects: [
      { type: EffectType.Static, id: EffectId.OpponentNeedsMoreCivilToWin },
    ],
    art: "/cards/monuments/civil-service.png",
  },
  {
    id: MonumentId.ModelSociety,
    kind: CardKind.Monument,
    name: "Model Society",
    district: District.Smarbbit,
    symbols: [Symbol.Scales],
    text: "You can now have 2 alliances in a district.",
    effects: [{ type: EffectType.Static, id: EffectId.AllianceLimitTwo }],
    art: "/cards/monuments/model-society.png",
  },
  {
    id: MonumentId.SmartDoctrine,
    kind: CardKind.Monument,
    name: "Smart Doctrine",
    district: District.Smarbbit,
    symbols: [Symbol.Atom, Symbol.Chart, Symbol.Crown, Symbol.Scales],
    text: "You may decide whether to host policy referendum before or after tallying for general election wins.",
    effects: [
      {
        type: EffectType.Triggered,
        id: EffectId.SmartDoctrineReferendumOrder,
        when: TriggerWhen.ElectionEndStart,
      },
    ],
    art: "/cards/monuments/smart-doctrine.png",
  },
];

export const POLICIES: PolicyCard[] = [
  {
    id: PolicyId.DragonaraA,
    kind: CardKind.Policy,
    name: "Currency Ballots",
    district: District.Dragonara,
    side: PolicySide.A,
    symbol: Symbol.Atom,
    text: "When you play a card in Dragonara, immediately draw a card then discard a card from hand.",
    effects: [
      {
        type: EffectType.Triggered,
        id: EffectId.CurrencyBallots,
        when: TriggerWhen.PlayInDistrict,
      },
    ],
    art: "/cards/policies/dragonara-a.png",
  },
  {
    id: PolicyId.DragonaraB,
    kind: CardKind.Policy,
    name: "Populist Forum",
    district: District.Dragonara,
    side: PolicySide.B,
    symbol: Symbol.Chart,
    text: "Each discard in Dragonara now provides 2 influence each.",
    effects: [{ type: EffectType.Static, id: EffectId.PopulistForum }],
    art: "/cards/policies/dragonara-b.png",
  },
  {
    id: PolicyId.HorsardA,
    kind: CardKind.Policy,
    name: "Economic Reform",
    district: District.Horsard,
    side: PolicySide.A,
    symbol: Symbol.Chart,
    text: "Each played card in Horsard, even alliance, gains +3 influence.",
    effects: [{ type: EffectType.Static, id: EffectId.EconomicReform }],
    art: "/cards/policies/horsard-a.png",
  },
  {
    id: PolicyId.HorsardB,
    kind: CardKind.Policy,
    name: "Market Regulation",
    district: District.Horsard,
    side: PolicySide.B,
    symbol: Symbol.Crown,
    text: "Civil cards of 8 or higher cannot be played in Horsard.",
    effects: [{ type: EffectType.Static, id: EffectId.MarketRegulation }],
    art: "/cards/policies/horsard-b.png",
  },
  {
    id: PolicyId.ShavvinneA,
    kind: CardKind.Policy,
    name: "Martial Law",
    district: District.Shavvinne,
    side: PolicySide.A,
    symbol: Symbol.Crown,
    text: "Each player gets -1 alliance limit and can only use actions that discard up to 1 card in Shavvinne.",
    effects: [{ type: EffectType.Static, id: EffectId.MartialLaw }],
    art: "/cards/policies/shavvinne-a.png",
  },
  {
    id: PolicyId.ShavvinneB,
    kind: CardKind.Policy,
    name: "Secularism",
    district: District.Shavvinne,
    side: PolicySide.B,
    symbol: Symbol.Scales,
    text: "Civil cards in Shavvinne of 5 or lower each counts influence twice.",
    effects: [{ type: EffectType.Static, id: EffectId.Secularism }],
    art: "/cards/policies/shavvinne-b.png",
  },
  {
    id: PolicyId.SmarbbitA,
    kind: CardKind.Policy,
    name: "United Front",
    district: District.Smarbbit,
    side: PolicySide.A,
    symbol: Symbol.Scales,
    text: "Cards to be discarded in Smarbbit now go to opponent's pile instead.",
    effects: [{ type: EffectType.Static, id: EffectId.UnitedFront }],
    art: "/cards/policies/smarbbit-a.png",
  },
  {
    id: PolicyId.SmarbbitB,
    kind: CardKind.Policy,
    name: "Consultative Office",
    district: District.Smarbbit,
    side: PolicySide.B,
    symbol: Symbol.Atom,
    text: "You may set aside faced-up Smarbbit cards to be used in later turns. They don't count towards hand limit.",
    effects: [{ type: EffectType.Static, id: EffectId.ConsultativeOffice }],
    art: "/cards/policies/smarbbit-b.png",
  },
];

export const EXECUTIVE: ExecutiveCard[] = [
  {
    id: ExecutiveSide.EmergencyState,
    kind: CardKind.Executive,
    name: "Emergency State",
    side: ExecutiveSide.EmergencyState,
    text: "Can only use in the immediate turn after your opponent discards ANY card. In politics step, use the power to enter Election Phase.",
    effects: [
      {
        type: EffectType.FreeAction,
        id: EffectId.EmergencyState,
        when: TriggerWhen.Politics,
      },
    ],
    art: "/cards/executive/emergency-state.png",
  },
  {
    id: ExecutiveSide.LegalReview,
    kind: CardKind.Executive,
    name: "Legal Review",
    side: ExecutiveSide.LegalReview,
    text: "Can only use in the immediate turn after your opponent discards ANY card. In politics step, use the power to remove any policy.",
    effects: [
      {
        type: EffectType.FreeAction,
        id: EffectId.LegalReview,
        when: TriggerWhen.Politics,
      },
    ],
    art: "/cards/executive/legal-review.png",
  },
];
